language: c
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-1.6.5-linux64.tar.xz
  - tar xf arduino-1.6.5-linux64.tar.xz
  - sudo mv arduino-1.6.5 /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
  
install:
 - ln -s $PWD /usr/local/share/arduino/libraries/ArtNetE131Lib_esp8266
# - arduino --install-library "E131"
# boards manager not working on 1.6.7 - 1.6.8
 - arduino --pref "boardsmanager.additional.urls=http://arduino.esp8266.com/stable/package_esp8266com_index.json" --save-prefs
# install lib arduino json not working in 1.6.5
#  - arduino --install-library "ArduinoJson"
 - git clone https://github.com/forkineye/E131.git /usr/local/share/arduino/libraries/E131
 - arduino --install-boards esp8266:esp8266
 - arduino --board esp8266:esp8266:d1_mini --save-prefs
 - arduino --pref "compiler.warning_level=all" --save-prefs
 
script:
 - arduino --verify --board esp8266:esp8266:d1_mini $PWD/examples/receiveArtNet/receiveArtNet.ino
 
notifications:
  email:
    on_success: change
    on_failure: change
